apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: monitoring
  labels:
    app: thanos-querier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - name: thanos-querier
        image: quay.io/thanos/thanos:v0.35.0
        args:
          - "query"
          - "--log.level=debug"
          - "--log.format=logfmt"
          - "--grpc-address=0.0.0.0:10901"
          - "--http-address=0.0.0.0:9091"
          - "--store=prometheus-operated.monitoring.svc.cluster.local:10901"  # Cluster 1
          - "--store=a49957fd662254448b9f42ad5460e65c-c39068451c54cd76.elb.us-west-2.amazonaws.com:10901"  # Cluster 2
          - "--store.sd-dns-interval=30s"
        ports:
          - name: grpc
            containerPort: 10901
          - name: http
            containerPort: 9091
        env:
          - name: OBJSTORE_CONFIG
            valueFrom:
              configMapKeyRef:
                name: thanos-object-storage
                key: object-storage.yaml
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9091
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9091
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-querier
  namespace: monitoring
  labels:
    app: thanos-querier
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9091
      targetPort: 9091
    - name: grpc
      port: 10901
      targetPort: 10901
  selector:
    app: thanos-querier
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-object-storage
  namespace: monitoring
data:
  object-storage.yaml: |
    type: S3
    config:
      bucket: thanos-poc-storage27
      endpoint: s3.us-west-2.amazonaws.com
      region: us-west-2
