apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: monitoring
type: Opaque
stringData:
  thanos.yaml: |
    type: S3
    config:
      bucket: thanos-poc***
      endpoint: s3.us-west-2.amazonaws.com
      region: us-west-2
