apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar-public
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-kube-prometheus-prometheus
